### ISSUE TITLE
not able to download 

### ISSUE THREAD

**Issue by farooque056** [Suyimu/WRV2#2]
Hi,I am not able to download the file

**Comment by Suyimu** [comment]
Hi Farooque,

Thank you for reaching out. We're using the Chinese cloud storage service Kuake for file downloads. I’ve tested the link, and it appears to be working on my end. If you encounter any issues, feel free to contact me at my email: suyimu@tju.edu.cn.

Best regards

**Comment by Suyimu** [comment]
![微信图片_20241104171847](https://github.com/user-attachments/assets/0fe3bf4c-96b9-4762-9fa5-456e739b33b1)
